PrivateBin/docker-nginx-fpm-alpine

Dockerfile

The user `nobody` isn't in the group `www-data` which leads to php-fpm attempting to chown the socket but this fails with;
```ERROR: [pool www] failed to chown() the socket '/run/php-fpm.sock': Operation not permitted (1)```
Also updated nginx.conf for consistency but this is also ignored because the container doesn't start as root by default.
```the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2```
Environment is;
Ubuntu 16.04.6 LTS   4.4.0-1095-aws   docker://18.6.2

Fix group permissions

---

etc/s6/services/nginx/run

closes #42
- add test for existence of the pipe /var/run/php-fpm.sock

do not start nginx until /var/run/php-fpm.sock is available

---

.github/workflows/snyk-container-analysis.yml

Another GitHub action that looked useful.
I've had to login with my GitHub account at https://app.snyk.io to get a free API token (saved as a secret in ~~this repo~~ the org) though.

Add snyk container scanning CI

---

.github/workflows/snyk-container-analysis.yml

As noticed in https://github.com/PrivateBin/docker-nginx-fpm-alpine/pull/52#issuecomment-875021973 Sync fails in PRs.
It says:
> `snyk` requires an authenticated account. Please run `snyk auth` and try again.
Basically, it's the token secret it cannot (and of course also should not) access.
As such, I'd say we disable it for PRs…
https://github.com/PrivateBin/docker-nginx-fpm-alpine/pull/52/checks?check_run_id=3002306667

Disable Snyk for PRs

---

README.md

Hello,
I found that the Kubernetes manifest provided as an example on the readme file contains an error on the reference to the port. Specifically, on the liveness and readiness section. I just updated the port on both for pointing to the 8080. Another possibility for fixing this could be just declaring the following on the "ports" section of the container "privatebin":
```yaml
ports:
- name: http
containerPort: 8080
protocol: TCP
```
Thank you in advance!
Regards

Fix reference to port on liveness and readiness probes in README.md

---

Dockerfile

I've been reviewing the errors in the nightly and PR image builds of the last days. The nightlys failed in edge with errors downloading packages like these:
```
#27 0.115 fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
#27 0.338 fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
#27 0.871 Upgrading critical system libraries and apk-tools:
#27 0.872 (1/8) Purging ssl_client (1.33.1-r4)
#27 0.873 (2/8) Installing libcrypto3 (3.0.0-r0)
#27 0.945 (3/8) Installing libssl3 (3.0.0-r0)
#27 0.968 (4/8) Upgrading apk-tools (2.12.7-r0 -> 2.12.7-r1)
#27 1.088 (5/8) Purging libretls (3.3.3p1-r0)
#27 1.088 (6/8) Purging ca-certificates-bundle (20191127-r5)
#27 1.090 (7/8) Purging libssl1.1 (1.1.1k-r1)
#27 1.090 (8/8) Purging libcrypto1.1 …
```

handle corner case deleting temporary files

---

Dockerfile

An earlier issue (#68 - the first described issue) with a [dependency of the package manager in edge got solved upstream](https://gitlab.alpinelinux.org/alpine/aports/-/issues/13022#note_181802). Now we hit the next problem with busybox still using ssl_client, but that already got removed from it's dependencies in the process to upgrade it to openssl 3, resulting in:
```
#31 6.836 wget: can't execute 'ssl_client': No such file or directory
#31 6.837 wget: error getting response: Connection reset by peer
```
ssl_client will become obsolete when busybox gets migrated to openssl 3, but for now we need to still add it explicitly for current alpine edge, while this is being worked on. For the main release (3.14), this change causes warnings that it is already installed and that it can't be …

edge build: deal with ssl_client while busybox gets migrated to openssl 3

---

Dockerfile

I looked at yet another failed build run and it again occurred in the armv7 build of an edge image, same as in #68:
```
#27 43.28 rm: can't remove '/tmp/tmp.EdnMEJ/S.gpg-agent.extra': No such file or directory
```
That seemed like a bit more than a coincidence and I found [this very similar report](https://github.com/MatthewVance/nginx-build/issues/33) that might explain this. It, too, occurs in an armv7 environment (Raspberry Pi 2), but on Raspbian Stretch and with gpg 2. To quote their analysis:
> It seems gpg automatically starts gpg-agent and this behaviour cannot be disabled using the --no-use-agent option in GnuPG 2.x, as explained in the docs:
> 
> > `--use-agent`
> > `--no-use-agent`
> > This is dummy option. gpg always requires the agent.
> 
> gpg-agent creates the three sockets …

ensure gpg-agent is dead, before deleting the $GNUPGHOME

---

.github/workflows/build-images.yml
buildx.sh

As per an [earlier discussion](https://github.com/PrivateBin/docker-nginx-fpm-alpine/pull/70#issuecomment-928761214), we:
- do want edge build failures to be noticed, so we can fix issues preventively, before they hit us in an upgrade
- but would like to avoid them from preventing the stable image builds to get pushed, i.e. in the nightly image builds
Hence this PR suggests to move the edge builds into a second loop, after the stable builds. Failures in them will still cause the whole build to fail.

run all image builds in parallel, letting all builds conclude

---

README.md

Learned via an [issue in the helm chart](https://github.com/PrivateBin/helm-chart/issues/54) that we can substitute the init container running a chown by using the `fsGroup` security context.

replace init container with fsGroup in example k8s deployment

---

Dockerfile
buildx.sh

While testing with php81, currently only available in Alpine edge testing, for https://github.com/PrivateBin/PrivateBin/issues/875, I found that the ssl_client workaround for OpenSSL 3 is no longer needed and the smoke test fails to detect PHP errors, since it neither looks for "error" nor for upper case labels.

Cleanup edge build / improve smoke test

---

.github/rules.tsv

According to the upstream issues these both should be fixed (and included in a release) and can thus be removed.

Remove now fixed excluded ZAP rules

---

Dockerfile

This mitigates [CVE-2022-0778](https://security.alpinelinux.org/vuln/CVE-2022-0778). I'll tag this as 1.3.5-alpine3.15.1, which will push images of the same name to the container registry.

bump the alpine base image, ensures openssl 1.1.1n is installed

---

etc/nginx/http.d/site.conf

This removal here only applies to the static resources, the PHP content gets this set on the application level:
https://github.com/PrivateBin/PrivateBin/commit/6f3bb25b092cf33160d1a8d2071f7ca4e5cedcaa
fixes #105 - The duplication of the header on privatebin.net was solved in:
https://github.com/PrivateBin/privatebin.info-pelican/commit/4f8bc79f6cbd926b0ee75e93317075c56cee669b

remove Permission-Policy header

---

Dockerfile
README.md

This change:
- moves the new administrative scripts out of web root (hardening)
- adds the php CLI package to the default packages
- adds the script location to the PATH
- provide some documentation on how to use them in the running container

support running new administrative scripts

---

buildx.sh

Based on my mistake in https://github.com/PrivateBin/docker-nginx-fpm-alpine/pull/126#issuecomment-1364639264 and the discussion in https://github.com/PrivateBin/docker-nginx-fpm-alpine/commit/ac3b128bf69967c94a8e6c7e8bbf1f5926416fe9#r94178102 this logic may have grown to be a bit too complex or at least misleading.
My thinking here is that the build args and tag list are two different things, so maybe they would be best handled separately. I'm introducing default tags, which the "edge" case replaces and the "push" appends to. As we are explicitly in a bash script, I do make use of the `+=` bashism to append.

clear up the build arg & tag logic

---

Dockerfile
buildx.sh

In #123 we got the following error message reported for the S3 image:
```
PHP Fatal error:  Uncaught Error: Class "SimpleXMLElement" not found in /srv/vendor/aws/aws-sdk-php/src/Api/Parser/PayloadParserTrait.php:39
```
Upon running the [compatibility-test.php](https://github.com/aws/aws-sdk-php/blob/master/compatibility-test.php) from the AWS library in our image, we see that:
```
==================================
AWS SDK for PHP Compatibility Test
==================================
System requirements
-------------------
- Ensuring that the version of PHP is >= 5.5.0: [OK]
- Ensuring that detect_unicode is disabled: [OK]
- Ensuring that session.auto_start is disabled: [OK]
- Checking if the pcre extension is installed: [OK]
- Checking if the spl extension is installed: [OK]
- Checking …
```

add simplexml & curl modules for images with AWS library

---

Dockerfile
buildx.sh

supersedes #134 - from that PR's discussion:
> The error itself does make sense, though, as we don't have the php81-iconv package installed, which seems to be required by the polyfill:
> https://github.com/symfony/polyfill-mbstring/blob/8ad114f6b39e2c98a8b0e3bd907732c207c2b534/Mbstring.php#L484-L492
> 
> We could install [php81-iconv](https://pkgs.alpinelinux.org/package/v3.17/community/x86_64/php81-iconv) (+88 kiB installed size) so the polyfill works or install [php81-mbstring](https://pkgs.alpinelinux.org/package/v3.17/community/x86_64/php81-mbstring) (+1.05 MB installed size for the library and +568 kiB for it's oniguruma dependency) to make the use of the polyfill unnecessary and provide native mbstring performance.
> 
> [...]
> 
> My idea is to install the lighter iconv package in …

address S3 polyfill errors

---

Dockerfile

Hello,
I was getting the following error while trying to set up PrivateBin using local S3 in TrueNAS:
```
[error] 19#19: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Polyfill\Mbstring\iconv_strlen() in /srv/vendor/symfony/polyfill-mbstring/Mbstring.php:491
Stack trace:
#0 /srv/vendor/symfony/polyfill-mbstring/bootstrap80.php(57): Symfony\Polyfill\Mbstring\Mbstring::mb_strlen()
#1 /srv/vendor/mtdowling/jmespath.php/src/Lexer.php(343): mb_strlen()
#2 /srv/vendor/mtdowling/jmespath.php/src/Parser.php(76): JmesPath\Lexer->tokenize()
#3 /srv/vendor/mtdowling/jmespath.php/src/AstRuntime.php(42): JmesPath\Parser->parse()
#4 /srv/vendor/mtdowling/jmespath.php/src/Env.php(33): JmesPath\AstRuntime->__invoke()
#5 …
```

Fix polyfill errors when using S3

---

README.md

Concludes/closes #85 by documenting the links to the GitHub container registry.
Please do comment on the wording, grammar, etc.

document/link to the GitHub container registry

---

etc/php81/php-fpm.d/zz-docker.conf

This is related to the new environment variables mentioned in [PR #1070](https://github.com/PrivateBin/PrivateBin/pull/1070/files#diff-6397c118bc734691db7f3ee3cb0612c97aaf098d404a4a6f430afed97ba1f1be) over in the main project.
In order to use these with the container image, they need to be passed down to PHP - for safety reasons, php-fpm filters out all environment variables and the ones to be exposed to PHP have to be configured explicitly.

support AWS access tokens & some documentation

---

etc/nginx/http.d/site.conf

The PrivateBin site says:
> Additionally the instance should be secured by [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security).
So I figured I'd add a bit of documentation in case people want to enable HSTS for PrivateBin!

Add commented HSTS line to nginx site.conf

---

.github/workflows/build-images.yml
Dockerfile
buildx.sh
etc/php/conf.d/00-docker.ini
etc/s6/services/php-fpm83/run

With Alpine 3.19 we can use either PHP 8.2 or 8.3. Switching is not urgent, IMO, just want to prepare this without being in a rush.
Also removes a deprecated PHP config option and enables building s390 arch images.

upgrade to PHP 8.3

---

Dockerfile

This will become required with the next PrivateBin release (> 1.7.1), where we replaced some of the regex based validation with ctype function calls.
It adds [about 50 KiB](https://pkgs.alpinelinux.org/package/v3.19/community/x86_64/php83-ctype) in uncompressed size.
We can merge this now or wait until the next release actually occurs. I would prefer merging it ahead of time.

add ctype PHP extension

---

Dockerfile

Pre-depends on a release that includes https://github.com/PrivateBin/PrivateBin/pull/1244
- switch to packaged composer
- with composer config becoming part of the signed release archive, we no longer need to download them separately

composer improvements

---

Dockerfile

- fixes #192
- only install composer if necessary
- if simplexml is requested, also install it for PHP 8.2, so composer can detect it
- unset composer platform config, it preventes upgrades to later GCS library
- remove unused RAWURL

S3 image fixes

---

Dockerfile

Also undo now obsolete 8.2 fix for #193, composer now is on the same PHP release as the rest

Bump alpine from 3.19.1 to 3.20.0

---

etc/init.d/rc.local

This change makes the entrypoint script PATH dependent, but agnostic to the real location of the s6-svcscan binary, so it work both for alpine 3.20 as well as edge / future stable alpine releases. An alternative would be to detect the presence of the binary in /usr/bin and create a symlink to that into /bin.
Example failing nightly build: https://github.com/PrivateBin/docker-nginx-fpm-alpine/actions/runs/11376261631/job/31648434608
Caused by this change: https://gitlab.alpinelinux.org/alpine/aports/-/commit/d348893ddf28edb773ac69df7129b43b767d8418#bc2914fbfe731ad6ff1eb5c019c39433c87bcaf5_22_24

with s6 2.13.1.0 binaries live in /usr/bin instead of /bin

---

Dockerfile
buildx.sh
etc/s6/services/php-fpm84/run

composer related packages need to stay at PHP 8.3 until the composer package itself gets upgrade in Alpine. These 8.3 packages get removed again at the end of the image build. Closes #209.
When merged, I'll tag a separate release `1.7.6-alpine3.21-php8.4` so folks can choose that or the PHP 8.3 based `1.7.6-alpine3.21` image, in case there are any issues with it. As usual, we can't really test the cloud storage libraries ourselves and will have to rely on issue reports, should those libraries still not work on PHP 8.4.

upgrade to PHP 8.4 packages
